language: python
python:
  - "3.6.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip3 install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: coverage run --source=coolio --omit=*features* -m behave
sudo: false
cache: pip

after_success: 
  - coveralls
